### ISSUE TITLE
axis.text.x and axis.text.y

### ISSUE THREAD

**Issue by calligross** [calligross/ggthemeassist#15]
axis.text.x and axis.text.y should be added, but all values must be NULL until changed by the user.

**Comment by ottlngr** [comment]
Well, I'm not sure if all axis themes should be added for x & y separately. The UI would suffer and become less intuitive. Also I think not many people use these...

**Comment by calligross** [comment]
I just realise that it is quite often the case that you change the angle of the labels independently. I pushed a first implementation to dev, maybe we have to alter the ui, but I think it's a useful feature.

**Comment by ottlngr** [comment]
You might be right. I'll check out dev tomorrow and maybe rework the UI.

**Comment by calligross** [comment]
Maybe we should organize the UI following a more or less general workflow approach. I will have to work through the weekend, but may find some time to think about it.

**Comment by ottlngr** [comment]
That's a good idea.
The question should be: What do I change first? A useful order could be:

1. Titles (plot, axis, legend)
2. Fonts (size, style & angle)
3. Legend position
4. Panel (background, lines, grid)
5. ...

**Comment by ottlngr** [comment]
Well it's a bit confusing to have empty inputs. In my opinion it's not clear that axis.text changes both axis.text.x and axis.text.y as long as the inputs for x and y are empty. A conditional panel maybe?

**Comment by calligross** [comment]
Axis,text.x and .y overwrite axis.text so from my point of view, a conditional panel is not a solution. e.g. you change the text size for both (axis.text) but need to adjust the angle for the x-axis, you need both.

The values have to be NULL unless there is a change.

**Comment by calligross** [comment]
Closed by ba9b48b
