### ISSUE TITLE
Removing titles doesn't work

### ISSUE THREAD

**Issue by calligross** [calligross/ggthemeassist#19]
ggplotThemeAssist should set the labels to NULL if input is an empty string and original plot had labels.

**Comment by ottlngr** [comment]
I think my pull request fixes that

**Comment by calligross** [comment]
Check my solution, it prevents the empty labels

**Comment by ottlngr** [comment]
That's a fix.

**Comment by calligross** [comment]
Ok, I will merge dev into master and then we should check what's missing for a cran release.
