### ISSUE TITLE
miniPage-Layout

### ISSUE THREAD

**Issue by ottlngr** [calligross/ggthemeassist#2]
```
ui <- miniPage(
    gadgetTitleBar("ggplot Theme Assistant"),
    miniTabstripPanel(
      miniTabPanel("Axis", icon = icon('sliders'),
        miniContentPanel(
          fillCol(flex = c(5, 3, 2),
            plotOutput("ThePlot", width = 800, height = 400),
            fillRow(
              fillCol(.....
```

does not work properly on small screens like my 12,5'' (Inputs overlay the plot),that why I changed it initially to

```
ui <- miniPage(
    gadgetTitleBar("ggplot Theme Assistant"),
    miniTabstripPanel(
      miniTabPanel("Axis", icon = icon('sliders'),
        miniContentPanel(
         plotOutput("ThePlot", width = 800, height = 400),
          fillCol(flex = c(5, 3, 2),
            fillRow(
              fillCol(.....
```
which leads to scrollbars but avoids that overlay of plot and inputs.

**Comment by calligross** [comment]
On my 27" the spacing was rather ugly, there has to be a better solution.

**Comment by calligross** [comment]
I made some layout adjustments. Please give the improveUI branch a try.

**Comment by ottlngr** [comment]
Inputs do not overlay the plot anymore, but overlay each other (on small screens). Using absolute heights instead of relative heights could fix this. 70px or 80px should be okay for the inputs.

**Comment by calligross** [comment]
I fixed the height, please check if it fits to your resolution.

**Comment by ottlngr** [comment]
Works on small screen. Don't think many people work on 12'' screens like I do anyway...
