### ISSUE TITLE
Unfortunate window size

### ISSUE THREAD

**Issue by jemus42** [calligross/ggthemeassist#32]
The window size of the gadget seems to be fixed at a certain size, and in relation to the window the actual plot seems to be too big. The result is that the controls are hard to interact with, especially with dropdown menues.

[Here's a screencap to see what I mean](http://dump.jemu.name/2016-03-09_vve4x.mp4) (mp4)

- System: OSX 10.11.3 / Retina MBP 15"
- Tested both current GitHub and CRAN version

**Comment by calligross** [comment]
Which version of shiny are you using?

**Comment by calligross** [comment]
I just tried to set the plot to a relative size, it seems to work. I will push a bugfix later.

Thanks for bringing this up.

**Comment by calligross** [comment]
Could you install from the dev branch and give some feedback if the plot has now a correct size on your macbook?

```r
devtools::install_github('calligross/ggthemeassist', ref = 'dev')
```

**Comment by ottlngr** [comment]
Looks better on my 12": 
http://www.pic-upload.de/view-29987643/ggthemeassist_dev10032016.png.html

**Comment by jemus42** [comment]
![](http://dump.jemu.name/p3kLI.png)

Yep, looks better, thanks!
