### ISSUE TITLE
FR: Resizable plot dimensions

### ISSUE THREAD

**Issue by jemus42** [calligross/ggthemeassist#34]
Premise 1: ggplot2-tinkerers will obsessively place elements on plots so they fit perfectly
Premise 2: Plot element (e.g. legend position) positioning depends on plot dimensions (and size)
Premise 3: ggThemeAssist is a tool für ggplot2-tinkerers
Conclusion: Adjustable plot dimensions would be a good feature!

Use case: I mostly do ggplots for RMarkdown documents, so when I adjust legend positioning etc. the dimension in ggthemeassist don't match up my output dimensions, so my tinkering is for naught (or at least followed by more tinkering, outside the addin).

The plot preview wouldn't need to scale to arbitrary sizes, just aspect ratio adjustments with a fixed max size should do fine.

**Comment by calligross** [comment]
Closed by 3ed59e4
