### ISSUE TITLE
If selected gg object includes a theme or theme modifications, update UI presets

### ISSUE THREAD

**Issue by jemus42** [calligross/ggthemeassist#36]
Probably kinda related to #33, but for reasons of completionism…

I'm currently using my own theme preset for the use with my Rmd template which changes things like background color and axis size/color. It would be nice if the assistant could act on that and fill the UI presets with the already changed values, so it's easier to continue tinkering with a theme.

**Comment by calligross** [comment]
Strange, seems to be a bug. updateDefaults should exactly do that.

**Comment by calligross** [comment]
Ok, that was a little bit tricky. The problem occurred if the theme of the given ggobject had values which weren't available in the input widgets, e.g. RGB colors. Should be working now in dev. 

Please give some feedback.

**Comment by jemus42** [comment]
Seems to work fine, thanks!

![](http://dump.jemu.name/ERvyb.png)
