### ISSUE TITLE
Allow #RRGGBB strings as colors

### ISSUE THREAD

**Issue by jemus42** [calligross/ggthemeassist#39]
The bazillion preset colors are fine and all, but 

- A giant dropdown menu isn't that great with limited vertical space
- The casual ggplot tinkerer frowns upon the use of preset colors with arbitrary sounding names and hallows the glory of the superior hex string in standard `#RRGGBB` format, for we shall be forever grateful for its gift of 256^3 technically-but-not-actually-visibly-distinct-but-good-enough colors.

<small>Okay, my posts are getting weird. Need my morning coffee.</small>

**Comment by calligross** [comment]
Should be working in dev for now.
