### ISSUE TITLE
Bonus feature: Subtitles in ggplot2

### ISSUE THREAD

**Issue by ottlngr** [calligross/ggthemeassist#42]
Seen on Twitter: http://rud.is/b/2016/03/12/ggplot2%E3%81%A7%E5%AD%97%E5%B9%95-subtitles-in-ggplot2/

**Comment by jemus42** [comment]
Might be coming to ggplot directly :)

https://github.com/hadley/ggplot2/pull/1582

**Comment by ottlngr** [comment]
Nice!

**Comment by ottlngr** [comment]
#43 
Maybe larger textInputs would be useful for long subtitles and captions

**Comment by ottlngr** [comment]
#45
