### ISSUE TITLE
\n gets ignored in titles and labels

### ISSUE THREAD

**Issue by ottlngr** [calligross/ggthemeassist#44]
Setting plot.title to "Plot \n Title" gives
    Plot \n Title
in ggThemeAssist. 
Executing the resulting code gives (as expected)
    Plot
    Title

**Comment by ottlngr** [comment]
#43 
The problem disappears when using multirow HTML text inputs. 
![subtitle_caption](https://cloud.githubusercontent.com/assets/11619414/13833570/70f06560-ebe7-11e5-87d6-8608487d649d.png)

So maybe replacing all textInputs by an HTML input is worthwhile.

**Comment by jemus42** [comment]
Slightly related: I remember labels that were `expression()`s not being recognized properly, but since `expression()` is delicate enough to handle in R itself, I don't know how well it can be accustomed in the gadget.
