### ISSUE TITLE
ggThemeAssist result styles

### ISSUE THREAD

**Issue by calligross** [calligross/ggthemeassist#49]
At the moment, the results are one big theme string, e.g.

```r
gg + theme(panel.grid.minor = element_line(size = 0.7, colour = 'black'), 
    legend.text = element_text(size = 12), 
    panel.background = element_rect(size = 0.7))
```

I guess it wouldn't be that difficulty to add an option for results like this:

```r
gg <- gg + theme(panel.grid.minor = element_line(size = 0.7), colour = 'black') 
gg <- gg + theme(legend.text = element_text(size = 12)) 
gg <- gg + theme(panel.background = element_rect(size = 0.7))
```

What do you think? Is it worth the effort?

**Comment by ottlngr** [comment]
I don't like these multiple assignments.
And I think that a ggThemeAssist result string should be usable as an input string for ggThemeAssist as well.

**Comment by hrbrmstr** [comment]
i'm not sure folks will ever edit the resulting returned `function` object. i use multiple assignments b/c I think it makes the code cleaner and easier for me personally to work with (and i make some ok ggplots :-)

**Comment by calligross** [comment]
Anyway, I added an opional multiline mode. Just in case someone missed such a feature. :-)
