### ISSUE TITLE
Hide 'Subtitle & Caption' tab when not supported (shinyjs)

### ISSUE THREAD

**Issue by ottlngr** [calligross/ggthemeassist#50]
The idea is to hide the 'Subtitle & Caption' tab when these features are not supported by ggplot2 to avoid hassle for users that do not use the latest version of ggplot2 (e.g. CRAN version).

One could check `is.null(ggplot2::theme_get()$plot.subtitle)` and thus hide the panel.

I tried with using `shinyjs::toggle()` but did not get it run...

Following the example in the documentation I tried:
```
ui <- miniPage(
    useShinyjs(),
    ...,
    miniTabPanel(id = 'subcap', 'Subtitle and Caption',
    ...
)

server <- function(input, output, session) {
    oberve({
        toggle(id = 'input$subcap', condition = is.null(ggplot2::theme_get()$plot.subtitle)
    })
    ...
}
```

**Comment by calligross** [comment]
Check out the dev branch, it's already done. :-)

**Comment by ottlngr** [comment]
Seems like a missed quite a few commits...
