### ISSUE TITLE
Simple arrows missing at end of axis X and axis Y

### ISSUE THREAD

**Issue by adamkk** [calligross/ggthemeassist#56]
Congrats on integrating ggthemeassist with RStudi ! Well done :-)

On theme is required in academic publications is that each chart should have a simple white background, no grid and at the end of axis X and axis Y  (see example from economics).

Many people ask on rseek.org about this missing feature. Let's add this theme to ggplot2.

Best,
Adam
![supply-and-demand](https://cloud.githubusercontent.com/assets/7294451/14240604/836d26b6-fa46-11e5-93f4-3a2bd2649b6a.png)

**Comment by calligross** [comment]
Shouldn't be too hard to add, will look into it.

**Comment by ottlngr** [comment]
ggplot2 is a tool for data visualization. That means ggplot2 (usually) deals with actual data. Textbook graphs normally represent functional relations between two measures (like quantity and demand) that are independend of the actual scale and therefore use arrows on the axes to indicate a quantitative development.
ggplot2 is simply the wrong tool for making textbook-like graphs.

**Comment by calligross** [comment]
I just looked into this issue again, but as it turns out, this is no available theme element at the moment.

ggThemeAssist is not indented to add custom theme objects, so I wil close this issue for now.

Should I be wrong and this is a out of the box feature, please reopen.
